### ISSUE TITLE
Check ext-css rules performance

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/ExtendedCss#55] opened 2017-12-22 11:59 UTC
Do we need to improve it on our side?

```
facebook.com#?#.ego_column:-abp-has(a[href^="/campaign/landing"])
facebook.com#?#div[class*="pagelet "]:-abp-has(a[href^="/campaign/landing"])
facebook.com#?#div[id^="hyperfeed_story_id_"]:-abp-has(a[href="#"]:-abp-contains(Chartered))
facebook.com#?#div[id^="hyperfeed_story_id_"]:-abp-has(a[href="#"]:-abp-contains(Sponsored))
facebook.com#?#div[id^="hyperfeed_story_id_"]:-abp-has(a[href="#"]:-abp-properties(content: "Chartered"))
facebook.com#?#div[id^="hyperfeed_story_id_"]:-abp-has(a[href="#"]:-abp-properties(content: "Sponsored"))
facebook.com#?#div[id^="hyperfeed_story_id_"]:-abp-has(input[data-next-question-id])
```

```
gelbooru.com##[-abp-properties='*: *;base64,']
```

**Comment by ameshkov** [comment] 2018-01-31 20:51
Here's what we need in order to test that.

1. Record `applyRules` method performance

    What we need:
    * The total number of times applyRules was called
    * Total time spent
    * Avg time per call
    * Std deviation

2. Provide a method that will print it to the output
3. Check the popular websites we have ExtCss rules for

Also, it seems that Sizzle initialization is quite slow, please investigate.

**Comment by ameshkov** [comment] 2018-02-05 14:04
Regarding the Sizzle initialization, here's how it looks like:
https://uploads.adguard.com/up04_lpclt_CNN_-_Breaking_News_U.S._World_Weather_Entertainment__Video_News.png

**Comment by ameshkov** [comment] 2018-02-08 09:51
Here're some findings from my own testing.

### Performance

1. Instead of `Sizzle.selectors.pseudo` we should use [`Sizzle.selectors.setFilters`](https://github.com/jquery/sizzle/wiki#sizzleselectorssetfilterslowercase_name--function-elements-argument-not--)
    > These filters are run after a previous part of a selector has already returned results

    We'd better use it for all our custom slow pseudo-classes: `:has`, `:properties`, `:matches-css`, `:contains`

2. Something happened between the current state and version 1.0.9. Performance tests shows a result 5 times worse than it was. I've tried rolling back to the previous version of the extended-css-selector and it works flawlessly. We'll lose the reverse search mechanism, but it's not really important if we switch to `setFilters`

3. We need a performance test for the `:properties` pseudo. Smth like this:
    ```
        QUnit.test("Case 6. :properties selector", function(assert) {

        var selectorText = 'div[id^="case6-"]:has(div[class]:properties(content:*test))';
        var selector = new ExtendedSelector(selectorText);

        testPerformance(selector, assert);
        Profiler.print();
    });
    ```

4. `AsyncWrapper.runAsap` method is noticeably ineffective in given circumstances. We should be able to coalesce sequential calls to it.

5. `AsyncWrapper.runImmediatly` is better, but again, we can optimize `:properties` performance by 10% just by coalescing these calls.

### Coding style

1. The `StyleObserver.initialize` function works incorrectly if I create one more selector after it was called once. This is especially important in the case when `Sizzle.selectors.setFilters` is in use.

2. I don't like how `ignoredSheets` are passed to the `StyleObserver` at the moment. It should be an `ExtendedCss` constructor parameter, and it should be then passed down to the `StyleObserver` via something like `setIgnoredSheets` method.

**Comment by ameshkov** [comment] 2018-02-14 11:37
It'd be beneficial if filters devs could enable performance tracking by passing a special "debug" rule to the ExtCss: `##selector:debug`

**Comment by ameshkov** [comment] 2018-02-15 23:35
Restored what was lost and re-tested it.

> 1. Instead of Sizzle.selectors.pseudo we should use Sizzle.selectors.setFilters

This appears to be an utter bs. `setFilters` works differently and it is not fully equal to `pseudo`. To be precise, in a situation with a compound selector that uses multiple `setFilters` pseudos `div:has(x) > div:has(y)` the elements passed to the filter functions are unexpected. Might be a bug of Sizzle but I doubt anybody cares, there're no examples of anyone using `setFilters` on GH.

I've updated the comment accordingly: https://github.com/AdguardTeam/ExtendedCss/issues/55#issuecomment-364058745

**Comment by ameshkov** [comment] 2018-02-16 11:31
I've experimented with `tokenize` and despite it being an ugly workaround, it seems to be a working solution: https://github.com/AdguardTeam/ExtendedCss/tree/feature/issues/55_tokenize_patch

A note on ugliness: this whole mess is supposed to speed up **some** popular selectors and it's easy to construct a new slow one and nothing will help it. I swear this is the last time we're messing with optimizing sizzle.

Before:
![](https://uploads.adguard.com/up04_qxecn__Performance_tests.png)

After:
![](https://uploads.adguard.com/up04_7bhl2__Performance_tests.png)

**Comment by seanl-adg** [comment] 2018-02-16 12:44
On my end with feature/issues/55:
![2018-02-16](https://user-images.githubusercontent.com/22858651/36308023-3675946a-1362-11e8-976f-033cb5b7200d.png)
With your patch:
![2018-02-16 1](https://user-images.githubusercontent.com/22858651/36308024-36a8fc74-1362-11e8-80fc-128f4ecc6ad7.png)
So there is no significant difference. 
It is absolutely absurd that your small patch can make matching 10 times faster.

**Comment by ameshkov** [comment] 2018-02-16 12:46
Did you call `grunt build` before running the test after switching to another branch?

**Comment by ameshkov** [comment] 2018-02-16 14:03
Regarding point 2 of https://github.com/AdguardTeam/ExtendedCss/issues/55#issuecomment-364058745

The problem is not just that it happened, on the contrary, it is natural. What concerns me much more is that there is no unit-test that can catch this. We can't simply use timing, it's different everywhere.

Possible solution: while running a performance test catch and count calls of our custom pseudo functions and check how many times they were called.

1.0.9:
![](https://uploads.adguard.com/up04_v5ztd__Performance_tests.png)

master:
![](https://uploads.adguard.com/up04_vrv6x__Performance_tests.png)

**Comment by ameshkov** [comment] 2018-02-27 16:14
1. I’ve created two more PRs about the things we’ve discussed:
https://github.com/AdguardTeam/ExtendedCss/pull/66
https://github.com/AdguardTeam/ExtendedCss/pull/65

2. Commented on the “debugging info” PR:
https://github.com/AdguardTeam/ExtendedCss/pull/63

3. Regarding the issues outlined, point 2 is the last thing to resolve after everything is merged.

Also, I think it is crucial to replace the current reverse search mechanism with another one involving patching Sizzle. Check this commit for the details: https://github.com/AdguardTeam/ExtendedCss/pull/66/commits/c2da1753555f95e79ae26e9217463c51a7138d6f

Take it from here plz.

**Comment by seanl-adg** [comment] 2018-03-12 17:28
All the performance concerns were caused by `compilerCache` being missed. Simply calling `Sizzle.compile` on certain selectors restores the performance of the previous version. This is looks like a bug of Sizzle, and it seems that it is fixed in Sizzle's master branch.

**Comment by ameshkov** [comment] 2018-03-12 22:20
> and it seems to be fixed in Sizzle's master branch

Are you sure about that? There were no serious changes since the end of 2016

**Comment by ameshkov** [comment] 2018-03-12 22:32
To be resolved:

1. Lack of the reverse `:properties` matching in the case of a nested `:properties`. See this test (20 sec on my pc): https://github.com/AdguardTeam/ExtendedCss/pull/66/files#diff-98464bdb99d957c722dbfc979c3e45d0R154

    The easiest solution -- use my patch that extends `find` and adds `:properties` there. This patch lets Sizzle use `:properties` to find seed elements: https://github.com/AdguardTeam/ExtendedCss/pull/66/files#diff-c36d60f36fe150ccdd90064a942cde33R469

    One more benefit -- `getSelector` can be made a private method. 

2. How to catch this case (performance degrading after a change) in the future? Ideas?

**Comment by seanl-adg** [comment] 2018-03-13 02:54
> Are you sure about that? There were no serious changes since the end of 2016
Check the Sizzle commit history.

**Comment by seanl-adg** [comment] 2018-03-13 02:55
>Lack of the reverse :properties matching in the case of a nested :properties.

**Comment by ameshkov** [comment] 2018-03-13 09:47
> Check the Sizzle commit history.

Hehe, this commit is from December 2016, just one month after we took it :)

> It takes less than 6 seconds on my pc, please check again.

Fixing the compilation improved it a lot indeed.

> IMO, we have already modified Sizzle too much and it makes updating Sizzle harder

This is true regardless of the last patch.

**Closed** 2018-03-21 09:15 UTC
Labels: enhancement
